/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step3`; params?: Router.UnknownInputParams; } | { pathname: `/study/exercise`; params?: Router.UnknownInputParams; } | { pathname: `/study`; params?: Router.UnknownInputParams; } | { pathname: `/study/results`; params?: Router.UnknownInputParams; } | { pathname: `/vocab/create`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/lists/[listId]`, params: Router.UnknownInputParams & { listId: string | number; } } | { pathname: `/vocab/[vocabId]`, params: Router.UnknownInputParams & { vocabId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/step1`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/step2`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/step3`; params?: Router.UnknownOutputParams; } | { pathname: `/study/exercise`; params?: Router.UnknownOutputParams; } | { pathname: `/study`; params?: Router.UnknownOutputParams; } | { pathname: `/study/results`; params?: Router.UnknownOutputParams; } | { pathname: `/vocab/create`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/lists/[listId]`, params: Router.UnknownOutputParams & { listId: string; } } | { pathname: `/vocab/[vocabId]`, params: Router.UnknownOutputParams & { vocabId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/two${`?${string}` | `#${string}` | ''}` | `/two${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/step1${`?${string}` | `#${string}` | ''}` | `/onboarding/step2${`?${string}` | `#${string}` | ''}` | `/onboarding/step3${`?${string}` | `#${string}` | ''}` | `/study/exercise${`?${string}` | `#${string}` | ''}` | `/study${`?${string}` | `#${string}` | ''}` | `/study/results${`?${string}` | `#${string}` | ''}` | `/vocab/create${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step3`; params?: Router.UnknownInputParams; } | { pathname: `/study/exercise`; params?: Router.UnknownInputParams; } | { pathname: `/study`; params?: Router.UnknownInputParams; } | { pathname: `/study/results`; params?: Router.UnknownInputParams; } | { pathname: `/vocab/create`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/lists/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/vocab/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/lists/[listId]`, params: Router.UnknownInputParams & { listId: string | number; } } | { pathname: `/vocab/[vocabId]`, params: Router.UnknownInputParams & { vocabId: string | number; } };
    }
  }
}
